version: "3.9"

services:
  db:
    image: postgres:15
    container_name: geojunk-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: geojunk
      POSTGRES_PASSWORD: geojunk_password
      POSTGRES_DB: geojunkdb
    ports:
      - "5432:5432"
    volumes:
      - geojunk_data:/var/lib/postgresql/data

volumes:
  geojunk_data:
